appName: ecam-app
cmsName: ecam-cms
appImage: tanminkwan/ecam-app
cmsImage: tanminkwan/ecam-cms
domainName: app.ecampus.click
streamServerUrl: http://app.ecampus.click
databaseUri: 'postgresql://ecam:1q2w3e4r!!@ecam2.c9akrgwjyzgk.us-east-2.rds.amazonaws.com:5432/ecam'
redisUri: 'redis://ecam2.unj9tc.ng.0001.use2.cache.amazonaws.com:6379'
appReplicaCount: 2
cmsReplicaCount: 2
appNodePort: 30080
cmsNodePort: 30180
pvcName: efs-claim