apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service-lb
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: {{ .Values.appNodePort }}
