apiVersion: v1
kind: Secret
metadata:
  name: db-connections
type: Opaque
stringData:
  database-uri: 'postgresql://ecam:1q2w3e4r!!@ecam2.c9akrgwjyzgk.us-east-2.rds.amazonaws.com:5432/ecam'
  redis-uri: 'redis://ecam2.unj9tc.ng.0001.use2.cache.amazonaws.com:6379'