apiVersion: v1
kind: Service
metadata:
  name: ecam-cms-service-lb
spec:
  type: LoadBalancer
  selector:
    app: ecam-app-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30180