apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecam-ingress
  namespace: ecam
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
        - path: /contents/
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.cmsName }}-service-lb
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.appName }}-service-lb
              port:
                number: 80